<a href="https://colab.research.google.com/github/ktb5891/ML_lecture/blob/main/ex01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 
### ndarray

* N 차원의 배열(Array) 객체


In [ ]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3],[4, 5, 6]])

list1 = [1, 2, 3]
print('list1 :',list1)
print('list1 type :',type(list1))

array1 = np.array(list1)
print('array1 :',list1)
print('array1 type :',type(array1))

list1 : [1, 2, 3]
list1 type : <class 'list'>
array1 : [1, 2, 3]
array1 type : <class 'numpy.ndarray'>


In [ ]:
array1 = np.array([1,2,3])
print('array1 type :',type(array1))
print('array1 array 형태 :',array1.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [ ]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type :',type(array2))
print('array2 array 형태 :',array2.shape)

array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)


In [ ]:
array1 = np.array([1,2,3])
print('array1 type :',type(array1))
print('array1 array 형태 :',array1.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type :',type(array3))
print('array3 array 형태 :',array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [ ]:
print('array1 : {0}차원, array2 : {1}차원, array3 : {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 : 2차원


In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [ ]:
list2 = [1, 2, 'numpy']
array2 = np.array(list2)
print(array2, array2.dtype)
# list에는 서로 다른 type을 저장할 수 있으나,
# 정수와 문자열이 같이 있는 list를 배열로 변환하면 
# 모두 문자열 type로 됨

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# list에는 서로 다른 type을 저장할 수 있으나,
# 정수와 실수가 같이 있는 list를 배열로 변환하면 
# 모두 실수 type로 됨


['1' '2' 'numpy'] <U11
[1. 2. 3.] float64


In [ ]:
#  astype() : type을 변환해 줌

array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1 2 3] int32
[1. 2. 3.] float64


In [ ]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [ ]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [ ]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


## ndarray 생성하기 - arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [ ]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [ ]:
#  dtype 속성을 별도로 지정하지 않으면 dtype 이 float64 가 됨
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 shape 변경하기 - reshape()

In [ ]:
array1 = np.arange(10)
print('array1 :\n', array1)

array2 = array1.reshape(2, 5)
print('array2 :\n', array2)

# ValueError: cannot reshape array of size 10 into shape (3,3)
# array2 = array1.reshape(3, 3)
# print('array2 :\n', array2)

array3 = array1.reshape(5, 2)
print('array3 :\n', array3)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = np.arange(10)
print(array1)

# column axis 의 크기는 5로 하고
# row axis 의 크기를 column 크기에 맞추어 
# 자동으로 변환하기  --> 2 X 5 의 형태가 됨
array2 = array1.reshape(-1, 5)
print('array2 shape :',array2.shape)
print('array2 :\n',array2)

# row axis 크기를 5로 고정하고 column axis의 크기는
# row axis 크기에 맞추어서 자동으로 변환하기 <-- 5 X 2 의 형태가 됨
array3 = array1.reshape(5, -1)
print('array3 shape :',array3.shape)
print('array3 :\n',array3)


[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape : (5, 2)
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환함
# column axis 크기는 1로 하는 경우
array2d_1 = array1.reshape(-1, 1)
print('array2d_1 shape :',array2d_1.shape)
print('array2d_1 :\n',array2d_1)

array1d = array2d_1.reshape(-1,)
print('array1d shape :',array1d.shape)
print('array1d :\n',array1d)

array2d_1 shape : (5, 1)
array2d_1 :
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape : (5,)
array1d :
 [0 1 2 3 4]


In [ ]:
# ValueError: cannot reshape array of size 10 into shape (4)
array1 = np.arange(10)
# array4 = array1.reshape(-1, 4)

# ValueError: can only specify one unknown dimension
# array1.reshape(-1, -1)