<a href="https://colab.research.google.com/github/ktb5891/ML_lecture/blob/main/ex02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ndarray의 data set 선택하기 - indexing 하기
* 특정 위치에 있는 값 하나를 추출하기

In [ ]:
import numpy as np

array1 = np.arange(start=1, stop=10)
print('array1 :',array1)

value = array1[2]
print('value :',value)
print(type(value))
print('맨 마지막 값 :',array1[-1],', 맨 마지막에서 두 번째 값 :',array1[-2])


print(array1[0])
print(array1[8])
array1[0] = 10
array1[8] = 22
print('array1 :',array1)

array1 : [1 2 3 4 5 6 7 8 9]
value : 3
<class 'numpy.int32'>
맨 마지막 값 : 9 , 맨 마지막에서 두 번째 값 : 8
1
9
array1 : [10  2  3  4  5  6  7  8 22]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array1d :\n',array1d)
print('array2d :\n',array2d)

print('(row=0, column=0) index 에 해당하는 값 :',array2d[0,0])
print('(row=0, column=1) index 에 해당하는 값 :',array2d[0,1])
print('(row=1, column=0) index 에 해당하는 값 :',array2d[1,0])
print('(row=2, column=2) index 에 해당하는 값 :',array2d[2,2])

array1d :
 [1 2 3 4 5 6 7 8 9]
array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, column=0) index 에 해당하는 값 : 1
(row=0, column=1) index 에 해당하는 값 : 2
(row=1, column=0) index 에 해당하는 값 : 4
(row=2, column=2) index 에 해당하는 값 : 9


###  슬라이싱(slicing)

In [ ]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Fancy Indexing (팬시 인덱싱)

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0,1],2]
print('array3 :',array3)
print('array2d[[0,1],2] :',array3.tolist())

array4 = array2d[[0, 2], 0:2]
print('array2d[[0, 2], 0:2] :',array4)
print('array2d[[0, 2], 0:2] :',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] :',array5)
print('array2d[[0,1]] :',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array3 : [3 6]
array2d[[0,1],2] : [3, 6]
array2d[[0, 2], 0:2] : [[1 2]
 [7 8]]
array2d[[0, 2], 0:2] : [[1, 2], [7, 8]]
array2d[[0,1]] : [[1 2 3]
 [4 5 6]]
array2d[[0,1]] : [[1, 2, 3], [4, 5, 6]]


### Boolean Indexing (불린 인덱싱)

In [ ]:
array1d = np.arange(start=1, stop=10)
print('array1d :',array1d)

print('array1d > 5 :',array1d > 5)

arr_bool1 = array1d > 5
print('arr_bool1 :',arr_bool1)
print('arr_bool1 type :',type(arr_bool1))



array1d : [1 2 3 4 5 6 7 8 9]
array1d > 5 : [False False False False False  True  True  True  True]
arr_bool1 : [False False False False False  True  True  True  True]
arr_bool1 type : <class 'numpy.ndarray'>


In [ ]:
print('array1d :',array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 boolean indexing :',array3)


array1d : [1 2 3 4 5 6 7 8 9]
array1d > 5 boolean indexing : [6 7 8 9]


In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱싱으로 필터링하기 :',array3)

불린 인덱싱으로 필터링하기 : [6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱싱으로 필터링하기 :',array4)

일반 인덱싱으로 필터링하기 : [6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
target = []

print('array1d :',array1d)
print('list(range(0, 9)) :',list(range(0, 9)))

for i in [0, 1, 2, 3, 4, 5, 6, 7, 8]:
    if array1d[i] > 5:
        target.append(array1d[i])
        
array_selected = np.array(target)   
print(target)
print(type(target))
print(array_selected)
print(type(array_selected))

array1d : [1 2 3 4 5 6 7 8 9]
list(range(0, 9)) : [0, 1, 2, 3, 4, 5, 6, 7, 8]
[6, 7, 8, 9]
<class 'list'>
[6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
# array1 = np.arange(start=1, stop=10) [1 2 3 4 5 6 7 8 9]
print('array1 :',array1)
print(array1d[array1 > 5])

array1 : [1 2 3 4 5 6 7 8 9]
[6 7 8 9]


### 행렬의 정렬 - sort(), argsort()

In [ ]:
origin_array = np.array([3, 1, 9, 5])
print('np.sort() 호출 전 원본 행렬 :',origin_array)

원본 행렬 : [3 1 9 5]


* np.sort() 로 정렬하기 - 원본 행렬이 변경되지 않음


In [ ]:
sort_array1 = np.sort(origin_array)
print('np.sort() 호출 후 반환된 정렬 행렬 :', sort_array1)
print('np.sort() 호출 후 원본 행렬 :', origin_array)

no.sort() 호출 후 반환된 정렬 행렬 : [1 3 5 9]
no.sort() 호출 후 원본 행렬 : [3 1 9 5]


* ndarray.sort() 로 정렬하기 - 원본 행렬이 변경됨

In [ ]:
sort_array2 = origin_array.sort()
# origin_array.sort()
print('origin_array.sort() 호출 후 반환된 정렬 행렬 :', sort_array2)
print('origin_array.sort() 호출 후 원본 행렬 :', origin_array)


origin_array.sort() 호출 후 반환된 정렬 행렬 : None
origin_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


#### 내림차순정렬

In [ ]:
sort_array1_desc = np.sort(origin_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [ ]:
name = 'python'
name[0:5]
print(name)
print(name[0:6])
print(name[:])
# name[start:stop:offset]
# name[start:stop]  <-- offset : 1
# name[start:stop:1]  <-- offset : 1
# name[start:stop:2]  <-- offset : 2

list_numbers = [1,2,3,4,5]

print('list_numbers[:] :',list_numbers[:])
print('list_numbers[::1] :',list_numbers[::1])
print('list_numbers[::-1] :',list_numbers[::-1]) # [5, 4, 3, 2, 1]
print('list_numbers[::2] :', list_numbers[::2])
print('list_numbers[1::2] :',list_numbers[1::2])


python
python
python
list_numbers[:] : [1, 2, 3, 4, 5]
list_numbers[::1] : [1, 2, 3, 4, 5]
list_numbers[::-1] : [5, 4, 3, 2, 1]
list_numbers[::2] : [1, 3, 5]
list_numbers[1::2] : [2, 4]


In [ ]:
array2d = np.array([[8,12],
                    [7, 1]])

# row 방향으로 정렬됨
sort_array2d_axis0 =  np.sort(array2d, axis=0)
print('sort_array2d_axis0 :\n',sort_array2d_axis0)

# column 방향으로 정렬됨
sort_array2d_axis1 =  np.sort(array2d, axis=1)
print('sort_array2d_axis1 :\n',sort_array2d_axis1)


sort_array2d_axis0 :
 [[ 7  1]
 [ 8 12]]
sort_array2d_axis1 :
 [[ 8 12]
 [ 1  7]]


In [ ]:
origin_array = np.array([3, 1, 9, 5])
print(origin_array)

# indexes, indices  <-- index 복수
sort_indices = np.argsort(origin_array)
print(type(sort_indices))
print('정렬된 행렬 :',np.sort(origin_array))
# 정렬된 data 들의, 정렬되기 전의 index 를 배열로 반환함
print('행렬 정렬시 원본 행렬의 index :', sort_indices)

[3 1 9 5]
<class 'numpy.ndarray'>
정렬된 행렬 : [1 3 5 9]
행렬 정렬시 원본 행렬의 index : [1 0 3 2]


In [ ]:
origin_array = np.array([3, 1, 9, 5])
print(origin_array)
print(np.sort(origin_array)[::-1])

sort_indices_desc = np.argsort(origin_array)[::-1]
print('행렬의 내림차순 정렬시 원본 행렬의 index :',sort_indices_desc)

[3 1 9 5]
[9 5 3 1]
행렬의 내림차순 정렬시 원본 행렬의 index : [2 3 0 1]


#### key-value 형태의 데이터 ndarray로 생성하고
#### argsort()를 사용해서 key값 정렬하기

In [ ]:
score_dict = {'Paul':72,'Tom':98,'John':86,'Kate':92,'Mike':88}

list(score_dict.keys()) # ['Paul','Tom','John','Kate','Mike']
list(score_dict.values()) # [72, 98, 86, 92, 88]

print('list(score_dict.keys()) :',list(score_dict.keys()))
print('list(score_dict.values()) :',list(score_dict.values()))

name_array = np.array(list(score_dict.keys()))
score_array = np.array(list(score_dict.values()))

name_array = np.array(['Paul','Tom','John','Kate','Mike'])
score_array = np.array([72, 98, 86, 92, 88])

# score_array의 정렬된 값에 해당하는 
# 원본 행렬 index 를 반환하고 이를 사용해서
# name_array에서 name 값 추출하기
sort_indices = np.argsort(score_array)
print('sort_indices :',sort_indices)
name_array_sort = name_array[sort_indices]
socre_array_sort = score_array[sort_indices]
print('name_array_sort :',name_array_sort)
print('socre_array_sort :',socre_array_sort)

list(score_dict.keys()) : ['Paul', 'Tom', 'John', 'Kate', 'Mike']
list(score_dict.values()) : [72, 98, 86, 92, 88]
sort_indices : [0 2 4 3 1]
name_array_sort : ['Paul' 'John' 'Mike' 'Kate' 'Tom']
socre_array_sort : [72 86 88 92 98]


### 선형대수학 - 행렬의 내적과 전치행렬

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]]) 

B = np.array([[7, 8],
              [9, 10],
              [11,12]])

C = np.dot(A, B)
print('행렬 A, B의 내적 :\n',C)

행렬 A, B의 내적 :
 [[ 58  64]
 [139 154]]


In [ ]:
A = np.array([[1, 2],
              [3, 4]])
A_t = np.transpose(A)
print('A :\n',A)              
print('A_t :\n',A_t)    

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
B_t = np.transpose(B)
print('B :\n',B)              
print('B_t :\n',B_t) 

A :
 [[1 2]
 [3 4]]
A_t :
 [[1 3]
 [2 4]]
B :
 [[1 2]
 [3 4]
 [5 6]]
B_t :
 [[1 3 5]
 [2 4 6]]
