### DataFrame, list, dictionary, ndarray(numpy)

#### list, ndarray(numpy) 에서 DataFrame으로 변환하기

In [11]:
import pandas as pd
import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
arr1 = np.array(list1)

print('arr1 shape :',arr1.shape)
print('list1 type :', type(list1))
print('arr1 type :', type(arr1))
print('-'*60)

df_list1 = pd.DataFrame(list1, columns=col_name1)
print('df_list1 - 1차원 리스트로부터 생성한 DataFrame :\n',df_list1)
print('df_list1 shape :',df_list1.shape)
print('-'*60)

df_arr1 = pd.DataFrame(arr1, columns=col_name1)
print('df_arr1  - 1차원 ndarray부터 생성한 DataFrame :\n',df_arr1)
print('df_arr1 shape :',df_arr1.shape)
print('-'*60)


arr1 shape : (3,)
list1 type : <class 'list'>
arr1 type : <class 'numpy.ndarray'>
------------------------------------------------------------
df_list1 - 1차원 리스트로부터 생성한 DataFrame :
    col1
0     1
1     2
2     3
df_list1 shape : (3, 1)
------------------------------------------------------------
df_arr1  - 1차원 ndarray부터 생성한 DataFrame :
    col1
0     1
1     2
2     3
df_arr1 shape : (3, 1)
------------------------------------------------------------


In [14]:
# 컬럼이름으로 사용할 list(col_name2)
col_name2 = ['col1','col2','col3']

# 2행 X 3열 형태의  list 와 ndarray를 생성하고
# 이 list와 ndarray를 DataFrame으로 변환하기
list2 = [[1, 2, 3],
         [11, 22, 33]]
arr2 = np.array(list2)

print('arr2 shape :', arr2.shape)
print('-'*60)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('df_list2 - 2차원 리스트로부터 생성한 DataFrame :\n',df_list2)
print('df_list2 shape :',df_list2.shape)
print('-'*60)

df_arr2 = pd.DataFrame(arr2, columns=col_name2)
print('df_arr2 - 2차원 ndarray로부터 생성한 DataFrame :\n',df_arr2)
print('df_arr2 shape :',df_arr2.shape)
print('-'*60)



arr2 shape : (2, 3)
------------------------------------------------------------
df_list2 - 2차원 리스트로부터 생성한 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33
df_list2 shape : (2, 3)
------------------------------------------------------------
df_arr2 - 2차원 ndarray로부터 생성한 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33
df_arr2 shape : (2, 3)
------------------------------------------------------------


#### dictionary를 DataFrame으로 변환하기

In [16]:
# key는 컬럼명으로 매핑, Value는 list나 ndarray로 지정함
dict_data = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict_data = pd.DataFrame(dict_data)
print('dictionary 로부터 생성된 DataFrame :\n', df_dict_data)

dictionary 로부터 생성된 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33


#### DataFrame을 ndarray 로 변환하기

In [19]:
arr3 = df_dict_data.values
print('arr3 :\n',arr3)
print('arr3 type :',type(arr3))
print('arr3 shape :',arr3.shape)

arr3 :
 [[ 1  2  3]
 [11 22 33]]
arr3 type : <class 'numpy.ndarray'>
arr3 shape : (2, 3)


#### DataFrame(df_dict_data)을 list 와 dictionary 로 변환하기

In [23]:
# list 로 변환
list_df = df_dict_data.values.tolist()
print('list_df :\n',list_df)
print('list_df type :',type(list_df))
print('-'*60)


# dictionary로 변환
dict_df1 = df_dict_data.to_dict()
print('dict_df1 :\n',dict_df1)
print('dict_df1 type :',type(dict_df1))
print('-'*60)

dict_df2 = df_dict_data.to_dict('list')
print('dict_df2 :\n',dict_df2)
print('dict_df2 type :',type(dict_df2))
print('-'*60)


list_df :
 [[1, 2, 3], [11, 22, 33]]
list_df type : <class 'list'>
------------------------------------------------------------
dict_df1 :
 {'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}
dict_df1 type : <class 'dict'>
------------------------------------------------------------
dict_df2 :
 {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
dict_df2 type : <class 'dict'>
------------------------------------------------------------


### DataFrame 의 컬럼 데이터셋 Access 
* DataFrame의 컬럼 데이터셋의 생성과 수정은 []연산자를 사용해서 할 수 있음
* 새로운 컬럼에 값을 할당하려면 DataFrame[] 내에 새로운 컬럼명을 입력하고 값을 할당함 

In [24]:
train_df = pd.read_csv('train.csv') # csv파일이 DataFrame으로 변환됨
print('train_df type :',type(train_df))

train_df type : <class 'pandas.core.frame.DataFrame'>


In [39]:
# del train_df['Age_0'] <-- 컬럼 삭제하기

train_df.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [40]:
# 컬럼 추가하기
train_df['Age_0'] = 0
train_df.head()

------------------------------------------------------------


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

In [41]:
train_df['Age_by_10'] = 0
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  
0      0         A/5 21171   7.2500   NaN        S      0          0  
1      0          PC 17599  71.2833   C85        C      0          0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0          0  
3      0            113803  53.1000  C123        S      0          0  
4      0            373450   8.0500   NaN        S      0          0

In [42]:
train_df['Family_No'] = train_df['SibSp'] + train_df['Parch']
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0          0   
1      0          PC 17599  71.2833   C85        C      0          0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0          0   
3      0            113803  53.1000  C123        S      0          0   
4      0            373450   8.0500   NaN        S      0          0   

   Family_No  
0          1  
1          1  
2          0  
3          1  
4          0

* 기존 컬럼에 있는 값을 업데이트하려면
* 해당 컬럼에 업데이트 값을 그대로 지정함

In [43]:
train_df['Age_by_10'] = train_df['Age_by_10']  + 100
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0        100   
1      0          PC 17599  71.2833   C85        C      0        100   
2      0  STON/O2. 3101282   7.9250   NaN        S      0        100   
3      0            113803  53.1000  C123        S      0        100   
4      0            373450   8.0500   NaN        S      0        100   

   Family_No  
0          1  
1          1  
2          0  
3          1  
4          0

### DataFrame 데이터 삭제하기

* axis 로 삭제하기

In [45]:
train_drop_df = train_df.drop('Age_0', axis=1)
train_drop_df.head()

###################################################################
# train_df.drop() 을 실행하면 원본(train_df)의 정보를 가져와서
# 삭제하는 컬럼(Age_0)이 삭제된 새로운 DataFrame을 생성해서 반환함
#  ㄴ 원본(train_df)의 컬럼이 삭제되는 것이 아님
###################################################################


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S        100          1  
1      0          PC 17599  71.2833   C85        C        100          1  
2      0  STON/O2. 3101282   7.9250   NaN        S        100          0  
3      0            113803  53.1000  C123        S        100          1  
4      0            373450   8.0500   NaN        S        100          0

In [46]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0        100   
1      0          PC 17599  71.2833   C85        C      0        100   
2      0  STON/O2. 3101282   7.9250   NaN        S      0        100   
3      0            113803  53.1000  C123        S      0        100   
4      0            373450   8.0500   NaN        S      0        100   

   Family_No  
0          1  
1          1  
2          0  
3          1  
4          0

#### DataFrame 에서 여러 개의 컬럼을 삭제하기
* 여러 개의 컬럼을 삭제하려면 drop()의 argument로 삭제하고자 하는 컬럼들의 이름을 문자열로 해서 리스트에 담아서 넣어줌


In [55]:
train_drop_cols = train_df.drop(['Age_0','Age_by_10','Family_No'], axis=1, inplace=True)
print('train_drop_cols :',train_drop_cols) # None



KeyError: "['Age_0' 'Age_by_10' 'Family_No'] not found in axis"

In [56]:
train_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [59]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('----- axis=0 으로 drop 하기 전 -----')
train_df.head(3)

# axis=0 :  row 방향으로 삭제 됨
# row의 index : [0, 1, 2]
# 아래의 code를 실행하면 0 번째, 1 번째, 2 번째 row가 삭제됨
train_df.drop([0, 1, 2], axis=0, inplace=True)
print('----- axis=0 으로 drop  한 후 -----')
train_df.head(3)

----- axis=0 으로 drop 하기 전 -----
----- axis=0 으로 drop  한 후 -----


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

### index  객체

In [62]:
# 원본 파일 다시 로딩하기
train_df = pd.read_csv('train.csv')

# index 추출하기
indexes = train_df.index
print(indexes)

# index 객체를 array로 변환하기
print('index 객체 array :\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
index 객체 array :
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232

In [67]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [69]:
# Index does not support mutable operations
# index 객체에는 [] 연산자를 사용해서 값을 변경할 수 없음
# indexes[0] = 33

In [70]:
series_fare = train_df['Fare']
series_fare.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [78]:
print('Fare Series max 값 :',series_fare.max())
print('Fare Series sum 값 :',series_fare.sum())
print('sum(series_fare)   :',sum(series_fare))

# 각 row마다 3이 더해짐
# index는 data를 구별하는 역할만 하고
# 실제 연산이 이루어질 때 연산되어지지는 않음
print((series_fare + 3).head())
print('-'*60)
series_fare.head()

Fare Series max 값 : 512.3292
Fare Series sum 값 : 28693.9493
sum(series_fare)   : 28693.949299999967
0    10.2500
1    74.2833
2    10.9250
3    56.1000
4    11.0500
Name: Fare, dtype: float64
------------------------------------------------------------


0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [79]:
train_df_reset = train_df.reset_index(inplace=False)
train_df_reset.head()    

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3      3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4      4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S

In [80]:
train_df.head()

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S

In [81]:
train_df.shape

(891, 12)

In [82]:
train_df_reset.shape

(891, 13)

In [84]:
print("----- reset_index() 실행 전 -----")
value_counts = train_df['Pclass'].value_counts()
print('value_counts :\n',value_counts)
print('type(value_counts) :',type(value_counts))

print("----- reset_index() 실행 후 -----")
reset_value_counts = value_counts.reset_index(inplace=False)
print('reset_value_counts :\n',reset_value_counts)
print('type(reset_value_counts) :',type(reset_value_counts))


----- reset_index() 실행 전 -----
value_counts :
 3    491
1    216
2    184
Name: Pclass, dtype: int64
type(value_counts) : <class 'pandas.core.series.Series'>
----- reset_index() 실행 후 -----
reset_value_counts :
    index  Pclass
0      3     491
1      1     216
2      2     184
type(reset_value_counts) : <class 'pandas.core.frame.DataFrame'>
